GET http://localhost:8080/cocktails?search=GG
Accept: application/json
Content-Type: application/json

### Below request will get all cocktails

GET http://localhost:8080/cocktails
Accept: application/json
Content-Type: application/json