GET http://localhost:8080/shopping-lists/
Accept: application/json
Content-Type: application/json

### get all shopping lists

GET http://localhost:8080/shopping-lists/a198ae01-955a-4eaf-b5ac-5aeabb287cbd
Accept: application/json
Content-Type: application/json
